Managers:
  test_manager: fluidhandler.managers.device_manager:DeviceManager

TestManager:
  test_component:
    module: fluidhandler.components.test_device:TestComponent
    enabled: true
    foo: 1
    bar: 2
    baz: 3
